#!/usr/bin/env python3
"""Package a run directory's raw traces + analysis for the repo (user decision: raw data is committed, sharded).
Usage: shard_traces.py --run-dir <WORKDIR>/runs/<run_id> --dest docs/<sweep>/runs/<run_id> [--max-mb 45]
Copies: req.json, meta.json, run_manifest.json, model_config.json, outputs/generations.jsonl, analysis/*.json,
        analysis/*.parquet (small), traces/indexer_trace.jsonl + traces/moe_trace.jsonl as gzip, split into
        <name>.jsonl.gz.partNN of at most --max-mb each (GitHub hard limit 100 MB, warning at 50 MB).
Writes dest/SHARDS.json with sha256 of every file and the reassembly command
  (cat traces/indexer_trace.jsonl.gz.part* | gunzip > traces/indexer_trace.jsonl).
Parquet evidence tables are NOT copied (they are regenerated by ingest_trace_fast.py from the JSONL).
All paths inside the copied JSON files are scrubbed to <WORKDIR>.
"""
import argparse, gzip, hashlib, json, os, shutil

ap = argparse.ArgumentParser()
ap.add_argument("--run-dir", required=True)
ap.add_argument("--dest", required=True)
ap.add_argument("--max-mb", type=int, default=45)
ap.add_argument("--no-traces", action="store_true", help="package manifests/analysis only")
a = ap.parse_args()
W = os.environ.get("WORKDIR", "")
os.makedirs(os.path.join(a.dest, "traces"), exist_ok=True)
os.makedirs(os.path.join(a.dest, "analysis"), exist_ok=True)
os.makedirs(os.path.join(a.dest, "outputs"), exist_ok=True)


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for c in iter(lambda: f.read(1 << 20), b""):
            h.update(c)
    return h.hexdigest()


def copy_scrubbed(src, dst):
    if src.endswith(".json") or src.endswith(".jsonl"):
        txt = open(src).read().replace(W, "<WORKDIR>").replace(os.path.expanduser("~"), "<HOME>")
        open(dst, "w").write(txt)
    else:
        shutil.copyfile(src, dst)


files = {}
for rel in ["req.json", "meta.json", "run_manifest.json", "model_config.json", "outputs/generations.jsonl"]:
    s = os.path.join(a.run_dir, rel)
    if os.path.exists(s):
        d = os.path.join(a.dest, rel)
        copy_scrubbed(s, d)
        files[rel] = sha(d)
an = os.path.join(a.run_dir, "analysis")
if os.path.isdir(an):
    for fn in sorted(os.listdir(an)):
        if fn.endswith(".json") or fn.endswith(".parquet") or fn.endswith(".log"):
            s, d = os.path.join(an, fn), os.path.join(a.dest, "analysis", fn)
            if os.path.getsize(s) > a.max_mb * 1024 * 1024:
                continue
            copy_scrubbed(s, d)
            files["analysis/" + fn] = sha(d)
limit = a.max_mb * 1024 * 1024
for name in ([] if a.no_traces else ["indexer_trace.jsonl", "moe_trace.jsonl"]):
    s = os.path.join(a.run_dir, "traces", name)
    if not os.path.exists(s):
        continue
    tmp = os.path.join(a.dest, "traces", name + ".gz")
    with open(s, "rb") as fi, gzip.open(tmp, "wb", compresslevel=6) as fo:
        shutil.copyfileobj(fi, fo, 1 << 20)
    size = os.path.getsize(tmp)
    n = 0
    with open(tmp, "rb") as f:
        while True:
            chunk = f.read(limit)
            if not chunk:
                break
            part = f"{tmp}.part{n:02d}"
            open(part, "wb").write(chunk)
            files[f"traces/{name}.gz.part{n:02d}"] = sha(part)
            n += 1
    os.remove(tmp)
    files[f"traces/{name}.gz"] = {"parts": n, "gz_bytes": size, "raw_bytes": os.path.getsize(s), "raw_sha256": sha(s)}
json.dump({"run_id": os.path.basename(a.run_dir.rstrip("/")), "max_part_mb": a.max_mb, "files": files,
           "reassemble": "cat traces/<name>.jsonl.gz.part* | gunzip > traces/<name>.jsonl; then scripts/gpu/ingest_trace_fast.py <run_dir>"},
          open(os.path.join(a.dest, "SHARDS.json"), "w"), indent=1)
print(f"[shard] {a.dest}: {len(files)} entries")
